### ISSUE TITLE
About release date.

### ISSUE THREAD

**Issue by sea2603** [kimiyoung/transfer#1]
Good paper, but is there still a plan on releasing source code after you've published the paper half a year up to now?

**Comment by felixwzh** [comment]
Good paper, but is there still a plan on releasing source code after you've published the paper half a year up to now?

**Comment by grafael** [comment]
@kimiyoung Still in your plans release the codes? If so will be plain C++, Tensorflow, pytorch... etc ?

**Comment by kimiyoung** [comment]
The data splits and code have been released. Sorry about the delay.
